#if defined _zm_class_consts_included
  #endinput
#endif
#define _zm_class_consts_included

stock const ZM_CLASS_ID[] = "id";
stock const ZM_CLASS_PARENT[] = "parent";
stock const ZM_CLASS_NAME[] = "name";
stock const ZM_CLASS_DESC[] = "desc";
stock const ZM_CLASS_MODEL[] = "model";
stock const ZM_CLASS_HEALTH[] = "health";
stock const ZM_CLASS_MAXSPEED[] = "maxspeed";
stock const ZM_CLASS_GRAVITY[] = "gravity";
stock const ZM_CLASS_WEAPONS[] = "weapons";
