#if defined _zm_classes_consts_included
  #endinput
#endif
#define _zm_classes_consts_included

#define Class: Trie:

stock const ZM_CLASS_NAME[] = "class_name";
stock const ZM_CLASS_DESC[] = "class_desc";
stock const ZM_CLASS_MODEL[] = "class_model";
stock const ZM_CLASS_HEALTH[] = "class_health";
stock const ZM_CLASS_MAXSPEED[] = "class_maxspeed";
stock const ZM_CLASS_GRAVITY[] = "class_gravity";
stock const ZM_CLASS_WEAPONS[] = "class_weapons";
